SARVAM_TTS_MODELS = ("bulbul:v2", "bulbul:v3")
SARVAM_V2_VOICES = (
    "anushka",
    "manisha",
    "vidya",
    "arya",
    "abhilash",
    "karun",
    "hitesh",
)
SARVAM_V3_VOICES = (
    "shubh",
    "aditya",
    "ritu",
    "priya",
    "neha",
    "rahul",
    "pooja",
    "rohan",
    "simran",
    "kavya",
    "amit",
    "dev",
    "ishita",
    "shreya",
    "ratan",
    "varun",
    "manan",
    "sumit",
    "roopa",
    "kabir",
    "aayan",
    "ashutosh",
    "advait",
    "amelia",
    "sophia",
    "anand",
    "tanya",
    "tarun",
    "sunny",
    "mani",
    "gokul",
    "vijay",
    "shruti",
    "suhani",
    "mohit",
    "kavitha",
    "rehan",
    "soham",
    "rupali",
)

# Full Sarvam catalog with display metadata. Sarvam has no list-voices API,
# so this is the source of truth for the voice picker.
# (voice_id, display name, gender, style)
SARVAM_V2_VOICE_CATALOG: tuple[tuple[str, str, str, str], ...] = (
    ("anushka", "Anushka", "female", "Warm"),
    ("manisha", "Manisha", "female", "Clear"),
    ("vidya", "Vidya", "female", "Professional"),
    ("arya", "Arya", "female", "Bright"),
    ("abhilash", "Abhilash", "male", "Steady"),
    ("karun", "Karun", "male", "Deep"),
    ("hitesh", "Hitesh", "male", "Conversational"),
)
SARVAM_V3_VOICE_CATALOG: tuple[tuple[str, str, str, str], ...] = (
    ("shubh", "Shubh", "male", "Confident & Bold"),
    ("aditya", "Aditya", "male", "Modern & Crisp"),
    ("ritu", "Ritu", "female", "Expressive & Lively"),
    ("priya", "Priya", "female", "Cheerful & Engaging"),
    ("neha", "Neha", "female", "Energetic & Warm"),
    ("rahul", "Rahul", "male", "Deep & Authoritative"),
    ("pooja", "Pooja", "female", "Cheerful & Engaging"),
    ("rohan", "Rohan", "male", "Confident & Bold"),
    ("simran", "Simran", "female", "Rich & Mature"),
    ("kavya", "Kavya", "female", "Polished & Articulate"),
    ("amit", "Amit", "male", "Steady & Trustworthy"),
    ("dev", "Dev", "male", "Casual & Relatable"),
    ("ishita", "Ishita", "female", "Polished & Articulate"),
    ("shreya", "Shreya", "female", "Energetic & Warm"),
    ("ratan", "Ratan", "male", "Rich & Mature"),
    ("varun", "Varun", "male", "Casual & Relatable"),
    ("manan", "Manan", "male", "Clear & Professional"),
    ("sumit", "Sumit", "male", "Deep & Authoritative"),
    ("roopa", "Roopa", "female", "Warm"),
    ("kabir", "Kabir", "male", "Rich & Cinematic"),
    ("aayan", "Aayan", "male", "Professional & Clear"),
    ("ashutosh", "Ashutosh", "male", "Traditional & Narrative"),
    ("advait", "Advait", "male", "Calm"),
    ("amelia", "Amelia", "female", "Soft"),
    ("sophia", "Sophia", "female", "Bright"),
    ("anand", "Anand", "male", "Friendly"),
    ("tanya", "Tanya", "female", "Conversational"),
    ("tarun", "Tarun", "male", "Clear"),
    ("sunny", "Sunny", "male", "Upbeat"),
    ("mani", "Mani", "male", "Natural"),
    ("gokul", "Gokul", "male", "Warm"),
    ("vijay", "Vijay", "male", "Confident"),
    ("shruti", "Shruti", "female", "Clear"),
    ("suhani", "Suhani", "female", "Gentle"),
    ("mohit", "Mohit", "male", "Conversational"),
    ("kavitha", "Kavitha", "female", "Professional"),
    ("rehan", "Rehan", "male", "Modern"),
    ("soham", "Soham", "male", "Calm"),
    ("rupali", "Rupali", "female", "Expressive"),
)
SARVAM_LANGUAGES = (
    "bn-IN",
    "en-IN",
    "gu-IN",
    "hi-IN",
    "kn-IN",
    "ml-IN",
    "mr-IN",
    "od-IN",
    "pa-IN",
    "ta-IN",
    "te-IN",
    "as-IN",
)
SARVAM_STT_MODELS = ("saarika:v2.5", "saaras:v3")
# saarika:v2.5 language codes (unknown = auto-detect)
SARVAM_STT_LANGUAGES_V25 = (
    "unknown",
    "hi-IN",
    "bn-IN",
    "gu-IN",
    "kn-IN",
    "ml-IN",
    "mr-IN",
    "od-IN",
    "pa-IN",
    "ta-IN",
    "te-IN",
    "en-IN",
)
# saaras:v3 adds these regional languages on top of the v2.5 set. Full list: https://docs.sarvam.ai/api-reference-docs/speech-to-text/transcribe
SARVAM_STT_LANGUAGES_V3 = SARVAM_STT_LANGUAGES_V25 + (
    "as-IN",
    "ur-IN",
    "ne-IN",
    "kok-IN",
    "ks-IN",
    "sd-IN",
    "sa-IN",
    "sat-IN",
    "mni-IN",
    "brx-IN",
    "mai-IN",
    "doi-IN",
)
SARVAM_LLM_MODELS = (
    "sarvam-30b",
    "sarvam-105b",
)
